#!/usr/bin/env python3
#
# Copyright (C) 2012 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import sys
import inspect

# Retrieve the path to the currently executed file
cur_file = os.path.abspath(inspect.getfile(inspect.currentframe()))

# Is it a symbolic link?
if os.path.islink(cur_file):
    cur_path = os.readlink(cur_file)
else:
    cur_path = cur_file

# Convert to directory name
cur_dir = os.path.dirname(cur_path)

# Append source directory to the path, if exists.
if os.path.exists(cur_dir + "/source/bouwer/__init__.py"):
    sys.path.insert(1, cur_dir + "/source")

import bouwer.core

if __name__ == '__main__':
    bouwer.core.execute()
